name: CI/CD Workflow

# Trigger on pushes and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      
      # Run tests
      - name: Run tests
        run: npm test

      # Build project
      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy to server or cloud provider
      - name: Deploy
        run: |
          echo "Deploying application..."
          # Add deployment script/commands here
